settings:
  legacy:
    force: true
    interval: 0s
schema:
  - name: go-echo-docker
    path: .
    commands:
      install:
        status: true
        method: go build -o app main.go
      run:
        status: true
        method: ./app
    watcher:
      extensions:
        - go
        - env
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor